### ISSUE TITLE
Will not work with ESP866

### ISSUE THREAD

**Issue by brownrb** [FancyFoxGems/HalfStepper#2]
It says one of the targets is expressif 8266, but I am using the Arduino IDE and when I use this library I get an error on [target Node MCU 1.0 ESP12E) - I am using the addon board manager http://arduino.esp8266.com/stable/package_esp8266com_index.json]

#include <avr/pgmspace.h>
from HalfSepper.h

Is this library compatible?
my basic code is 

#include "HalfStepper.h"

HalfStepper mystepper(2048, 13, 14, 2, 12);

void setup()
{
  mystepper.setSpeed(MOTORSPEEDRPM);
  delay(5);
}

void loop()
{
  // FULL STEPPING
  for ( int lp = 0; lp < 2048; lp++ )
  {
    mystepper.step(1);
    delay(1);
  }

  delay(1000);

  for ( int lp = 0; lp < 2048; lp++ )
  {
    mystepper.step(-1);
    delay(1)l
  }

  // NOW HALF STEPPING
  mystepper.SetSteppingMode(SteppingMode::HALF);
  for ( int lp = 0; lp < 2048; lp++ )
  {
    mystepper.step(1);
    delay(1);
  }

  delay(1000);
}

**Comment by FancyFoxGems** [comment]
I'm afraid that I completely overlooked that.  To make it compatible, try the following code change in the library source.

HalfStepper.h:27:
`#include <avr/pgmspace.h>`
   becomes
`#include <sys/pgmspace.h>`

I do not believe I have a board to test with, but it does compile for me.

**Comment by brownrb** [comment]
Awesome, thanks for the reply, I'll test it out and let you know.

Regards
Robert


     On Friday, July 26, 2019, 6:20:40 AM GMT+12, Fancy Fox Gems <notifications@github.com> wrote:  
 
 
I'm afraid that I completely overlooked that. To make it compatible, try the following code change in the library source.

HalfStepper.h:27:
#include <avr/pgmspace.h>
becomes
#include <sys/pgmspace.h>

I do not believe I have a board to test with, but it does compile for me.

**Comment by brownrb** [comment]
Apologies
Does not compile. 
sys/pgmspace.h: No such file or directory
I have target as Node MCU v1 ESP12-E
I added the HalStepper library via zip manager then edited the .h file as suggested.



     On Friday, July 26, 2019, 6:20:40 AM GMT+12, Fancy Fox Gems <notifications@github.com> wrote:  
 
 
I'm afraid that I completely overlooked that. To make it compatible, try the following code change in the library source.

HalfStepper.h:27:
#include <avr/pgmspace.h>
becomes
#include <sys/pgmspace.h>

I do not believe I have a board to test with, but it does compile for me.

**Comment by brownrb** [comment]
I have resolved this by modifying the halfstepper files myself. We now have the HalfStepperESP32,zip library.
